#!/bin/sh

/usr/bin/kernelshark &
pid=$!
win=`xdotool search --sync --onlyvisible --pid $pid`
echo "win=$win"
name=`xdotool getwindowname $win`
kill -9 $pid
echo "name=$name"
if [ "$name" = "Kernel Shark" ]; then
echo "Test OK"
return 0
else
echo "Test Failed"
return 1
fi
